#This is my 1st project...
 #build in python 
import calendar 
#input() ask user to enter the year...
year=int(input("enter year:"))
month=int(input("enter month:"))
#\n is escape sequence...new line...
print("\n",calendar.month(year,month))
