import random #is used to pick random chartrs..........
import tkinter as tk #tkinter is used to create GUI........
root=tk.Tk() #create the main window........
root.title("Random Password Generator")  #create title bar text.....
#add label to the window...
label=tk.Label(root,text="Random Password Generator",font=("Arial",16,"bold"))
label.pack()
#display this label on the window........
length_label=tk.Label(root,text="Enter Password Length",font=("Arial",8,"bold"))
length_label.pack()
#create an input box for the user to type passwrd length...
length_entry=tk.Entry(root,bd=1,relief="solid")
length_entry.pack(pady=5)  #display it with 5px vertical padding....
 # Create an input box to display the generated password....
password_entry=tk.Entry(root,width=30,bd=1,relief="solid")
password_entry.pack(pady=5)
 # Function that runs when GENERATE button is clicked....
def generate_password():
    try:   
            length=int(length_entry.get())   # Read the length entered by user and convert to integer....
            if length<=0:    # Check if the entered length is invalid (zero or negative)....
                password_entry.delete(0,tk.END)  # Clear any existing text in password box.....
                password_entry.insert(0,"Enter Valid length")  # Show error message instead of a password.......
                return
            #string containing all charactrs...
            characters="abcdefghijklmnopqrstuvwxyzABCDFGHIJKLMNOPQRSTUVWXYZ0123456789@$&*#"
            password="" # Start with an empty password string....
            for i in range(length):   # Loop 'length' times to build the password character by character...
                password+=random.choice(characters) # Randomly pick one character and add it to password...
            password_entry.delete(0,tk.END)   # Clear the password entry box before showing new password...
            password_entry.insert(0,password)  # Insert the newly generated password into the entry box....
    except ValueError:
        password_entry.delete(0, tk.END) # This runs if the user types letters instead of a number....
        password_entry.insert(0, "Enter the number")  # Ask user to enter a valid number....
    
   # Button that generates the password when clicked
generate_button=tk.Button(root,text="GENERATE",command=generate_password,bg="pink",fg="Black")
generate_button.pack() # without pack(), the button won't show up.....
root.mainloop()  # Keeps the window open and running (without this, window closes instantly)....